language: node_js
node_js:
  - "6"

env:
  global:
  - GH_PAGES_DEPLOY: YES
  - REPO_SLUG: candyHuang/vue-destop

install:
  - npm install

script: sh .deploy.sh

cache:
  directories:
  - node_modules
branches:
  only:
  - master
